kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/webhookrelay/relay-go

steps:
- name: build
  image: golang:1.12
  commands:
    - make install

- name: test
  image: golang:1.12
  commands:
    - make test-pretty 

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_url
    channel: general
    username: drone
    icon_url: https://i.pinimg.com/originals/51/29/a4/5129a48ddad9e8408d2757dd10eb836f.jpg
